version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dungcon2005
      MYSQL_DATABASE: campuslearning
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_container
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app-net
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-net

  redis-comment:
    image: redis:7-alpine
    container_name: redis_comment_container
    restart: always
    ports:
      - "6380:6379"
    networks:
      - app-net

  redis-conversation:
    image: redis:7-alpine
    container_name: redis_conversation_container
    restart: always
    ports:
      - "6381:6379"
    networks:
      - app-net

  redis-message:
    image: redis:7-alpine
    container_name: redis_message_container
    restart: always
    ports:
      - "6382:6379"
    networks:
      - app-net

  redis-story:
    image: redis:7-alpine
    container_name: redis_story_container
    restart: always
    ports:
      - "6383:6379"
    networks:
      - app-net

  # DÙNG IMAGE TỪ DOCKERHUB
  spring-app:
    #Khi nào CI/CD được thì comment cái build lại
    build:
      context: .                     # <-- MÀY MUỐN THÊM
      dockerfile: Dockerfile
    image: damdung/campuslearning-spring-app:latest
    container_name: spring_container_2
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
      redis-comment:
        condition: service_started
      redis-conversation:
        condition: service_started
      redis-message:
        condition: service_started
      redis-story:
        condition: service_started
    ports:
      - "8888:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/campuslearning
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: dungcon2005
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "false"
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_REDIS_COMMENT_HOST: redis-comment
      SPRING_REDIS_COMMENT_PORT: 6379
      SPRING_REDIS_CONVERSATION_HOST: redis-conversation
      SPRING_REDIS_CONVERSATION_PORT: 6379
      SPRING_REDIS_MESSAGE_HOST: redis-message
      SPRING_REDIS_MESSAGE_PORT: 6379
      SPRING_REDIS_STORY_HOST: redis-story
      SPRING_REDIS_STORY_PORT: 6379
    networks:
      - app-net
    volumes:
      - ./uploads:/app/uploads

  code-server:
    image: codercom/code-server:4.105.0
    container_name: code_server_container
    restart: always
    command: --auth none --bind-addr 0.0.0.0:8080
    ports:
      - "8100:8080"
    volumes:
      - ./workspace:/home/coder/project
    networks:
      - app-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./k8s:/etc/prometheus
    ports:
      - "9090:9090"
    networks:
      - app-net
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - app-net
    restart: always

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    ports:
      - "8686:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-net

networks:
  app-net:

volumes:
  mysql_data:
  jenkins_home: