apiVersion: v1
kind: Service
metadata:
  name: spring-be
spec:
  type: LoadBalancer
  selector:
    app: spring-be
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080