prometheus:
  server:
    service:
      type: ClusterIP
      port: 9090  # Prometheus K8s port nội bộ 9090
  additionalScrapeConfigs: |
    - job_name: 'spring-be-k8s'
      metrics_path: '/actuator/prometheus'
      static_configs:
        - targets: ['spring-be:80']

grafana:
  service:
    type: ClusterIP
    port: 3000  # Grafana port 3000